version: "3.8"
services:
  python:
    build: .
    depends_on:
      - db
    volumes:
      - ./code:/code
    command: bash -c "python /code/initial_db.py && tail -f /dev/null"

  db:
    image: postgres
    env_file:
      code/database.env
    volumes:
      - ./database-init:/docker-entrypoint-initdb.d
      - database-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]

  adminer:
    image: adminer
    ports:
      - 8080:8080

volumes:
  database-data:
